name: Setup Frontend
description: Checkout, setup pnpm/Node.js, and install dependencies for the frontend workspace

inputs:
  node-version:
    description: Node.js version
    required: false
    default: "20"
  pnpm-version:
    description: pnpm version
    required: false
    default: "9"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: applications/frontend/pnpm-lock.yaml

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      working-directory: applications/frontend
