name = "hut-prd-reader"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_URL = "https://hut.lihs.dev"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = ""
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = ""
READER_SITE_ORIGIN = "https://hut.lihs.dev"
SERVER_ACTIONS_ALLOWED_ORIGINS = "hut.lihs.dev"
IMAGE_REMOTE_PATTERNS = ""

[observability]
enabled = true
